name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Fixed Java setup with proper cache configuration
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          # Remove the built-in Gradle cache option as it's causing issues
          # We'll handle Gradle caching separately

      # Add explicit Gradle caching
      - name: Setup Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run tests
        run: ./gradlew test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker layer caching
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: |
          docker compose -f docker-compose.yml build

      - name: Start all services
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be ready..."
          sleep 45
          docker compose ps

      - name: Verify services health
        run: |
          # Check if Inventory Service is up
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8080/actuator/health || echo "Inventory Service health check failed"
          
          # Check if Order Service is up
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8081/actuator/health || echo "Order Service health check failed"

      # Stop services after testing
      - name: Stop services
        if: always()
        run: |
          docker compose -f docker-compose.yml down